### ISSUE TITLE
Google Ads Remarketing fails (sendPixelFromBrowser support)

### ISSUE THREAD

**Issue by mklewitz** [stape-io/data-client#5]
Hi,

Google Ads Remarketing fails when not the server container is invoked through Data Tag <-> Data Client. It does work with GA 4 Configuration/Event <-> GA4-Client, though.

I think that is because the Remarketing tag wants the browser to make a request to doubleclick and therefor probably calls sendPixelFromBrowser(). The GA4 web tags simply parses the (json) response of the GA4-Client, which contains info about the url to embed in the browser.

I tried to find out how sendPixelFromBrowser detects if the client supports it, but didn't succeed. If Data Client would be able to support sendPixelFromBrowser and retrieve the url, it should be more or less easy to return it to Data Tag, so that Data Tag can embed the pixel in browser.

Do you think that sendPixelFromBrowser support can be integrated?

Thanks!

**Comment by mklewitz** [comment]
Hi,

thanks for your answer. I'm trying to implement this and will make a pull request when ready!

Indeed the response at first looked promising when I attached "&richsstsse". However, cookies weren't set by Set-Cookie headers anymore, but somehow moved to send_pixel events. This is how a response looked like:

```event: message
data: {"send_pixel":["https://www.googleadservices.com/pagead/conversion/XXXXXXX/?random=..."]}

event: message
data: {"send_pixel":["${transport_url}/_set_cookie?val=VlPX624xi2oUC%2BGaS4Ota0UkObOaG4CqGfYZPXrlcSO3YByzVLWKhIJjVMjncEMP6QfanfMSt5V%2F9yBaLJt%2Fhs34SJeJejXxaj2Md7zvkZCkHnoeS3jXEnloLGTjOi%2FNZaIda7j%2BgoLpJo4mil07Rf%2FF77Nlz%2BUS9NQK"]}

event: message
data: {"response":{"status_code":200,"body":"{\"unique_event_id\":\"1680338446713_443922090\",\"custom\":\"\"}"}}```

The cookie in the example above is the _fbc cookie by stape's Facebook Conversion Api Tag. If the request is claimed by the GA4 client (with or without richsstsse), _fbc is set by a Set-Cookie header and there is no send_pixel for ${transport_url}/_set_cookie. However, if the request is claimed by Data Client with &richsstsse present there's no Set-Cookie header, but instead a send_pixel event for ${transport_url}/_set_cookie. 

I even manually set all the event data that is normally set by GA4 client, but that didn't do the trick. There must be something else that triggers the aforementioned behaviour. Any ideas? Thanks!

**Comment by Bukashk0zzz** [comment]
Happy to hear that you will make PR.

@mklewitz Try to remove the Data Client Standard answer. There are options in Data Client called empty response.
And it this does not help, then you can just send a request from the Data tag to "${transport_url}/_set_cookie?val=VlPX624xi2oUC%2BGaS4Ota0UkObOaG4CqGfYZPXrlcSO3YByzVLWKhIJjVMjncEMP6QfanfMSt5V%2F9yBaLJt%2Fhs34SJeJejXxaj2Md7zvkZCkHnoeS3jXEnloLGTjOi%2FNZaIda7j%2BgoLpJo4mil07Rf%2FF77Nlz%2BUS9NQK" and cookie will be decoded and stored for you.

GA4 client/tag also use this /_set_cookie path sometimes for set cookies. From my understanding, this is caused by the slow response of tags. In case FB tag provides gtmOnSucess to long sGTM response with this /_set_cookie thing. But that's not a fact just how I think this work.

**Comment by mklewitz** [comment]
My Data Client is already set to "empty response", cause I'm returning custom variables with the help of the json response tag. It seems, that the cookie behaviour isn't related to timing of tags, cause it also happens if I don't touch the server tags at all.
Without changing anything in the server container: If the request is claimed by GA4 client, set-cookie header is used. If it's claimed by Data Client, send_pixel cookies are returned.
